### ISSUE TITLE
Developer install does not work

### ISSUE THREAD

**Issue by rainman110** [helmholtz-analytics/mpi4torch#2]
Installing via ``python setup.py install`` works.

But installing via `` pip install -e .`` does not. This is however the preferred way for the development cycle.

**Comment by d1saster** [comment]
Just adding [PEP 660](https://peps.python.org/pep-0660/) for future reference here. So far I don't know how to make this work together with PEP 517 and 518.

**Comment by d1saster** [comment]
As it turns out PEP660 was implemented by setuptools in pypa/setuptools#3488 (part of the 64.0.0 release, which happened on Aug 11, 2022, so quite fresh) which according to my testing fixes this bug.

Since there are currently only few developers and the editable build is not the standard build, I feel reluctant to add `setuptools>=64.0.0` as a build requirement to pyproject.toml. Note that the issue can persist im you (very likely still) have an older version of setuptools in your pip cache. It is best to check with increased verbosity which version of setuptools is used for building mpi4torch, i.e. using `pip install -v -e .` when installing from a local checkout.

**Comment by d1saster** [comment]
And pip of course needs also to be younger than [21.3](https://pip.pypa.io/en/latest/news/#v21-3) to have PEP660 support.
